### ISSUE TITLE
removed group:view

### ISSUE THREAD

**Issue by sunkan85** [Gnaget2/Car-Heater-Package#10]
in new hassio they have removed group, I have no idea how to fix the code

Invalid config for [group]: [view] is an invalid option for [group]. Check: group->group->heater_view->view. (See ?, line ?).

**Comment by sunkan85** [comment]
with a little help I got it in order
row 288

# Group section
group:
  heater:
    name: "Motorvärmare"
    entities:
      - sensor.departuretime
#      - sensor.heater_start_time
      - input_number.heater_hour
      - input_number.heater_minutes
      - sensor.heater_outside_temp
      - light.motorvarmaren
      - input_boolean.heaterstatus
      - input_boolean.heaterweekday

**Comment by sunkan85** [comment]
. when i remowe row 288-295 and 300. hassio give ok on code. but now it do not trigger the switch

**Comment by Ryssk** [comment]
> . when i remowe row 288-295 and 300. hassio give ok on code. but now it do not trigger the switch

Question, when you say it doesnt trigger the switch. Are you sure it's below 5.0 degrees? Cause that's how the condition work for the automation. 

below: '5'

If you want it to be something else, then you propably want to use it if it's like below 8-10 degrees? Just change the below value between line 160 - 207

# triggers 30min before departure time when temp is below 5 and heater status is on, checks if weekend/weekday matches option

**Comment by sunkan85** [comment]
it is working now i run the automation manuell, and it trigged now. bot not befor maby i it was the temp or maby i did nott rebot hassio when i did have trubel. thx
