### ISSUE TITLE
Wont start at all

### ISSUE THREAD

**Issue by AcidSleeper** [Gnaget2/Car-Heater-Package#3]
Hey there

I have tried to get this started but no luck.
I use YR and changed the switch.heater to my switch and no problems in log.
Also Im running Hassio on RPi3 so I changed the time to the latest code fron recent Issue adressed. `((as_timestamp(now())|int - XXX)|timestamp_custom("%H:%M"))` Now it shows the right time i dev-tool.

But it will not activate.
Question:
 - If the time is 14:10, temperature is +1degree and I set departure time to 14:45 and XXX is -1800. Will it activate at 14:15?

I have no problems in compilation or log.

**Comment by Alealvag** [comment]
Hi,

-1800 would mean that it starts 30 min after the set time so I would guess you want to use +1800 to start 30 min before.

Andreas

22 oktober 2018 10:42:23 +02:00, skrev AcidSleeper <notifications@github.com>:

**Comment by AcidSleeper** [comment]
Okey. I havent changed that portion of the code so I guess I have to change the code a bit. 
But the code seems to work for the author!?

Is the code right but wrong when it comes to my as_timestamp...?

**Comment by Alealvag** [comment]
This is the way I had to do it to use the correct time. This particular value template triggers 2h before my set departure time.

`value_template: '{{ ((as_timestamp(now()) | int + 7200 ) | timestamp_custom("%H:%M")) == states.sensor.departuretime.state  }}'`

**Comment by AcidSleeper** [comment]
Couldnt find the fault with the code. Started from scratch and copied again but the same, wont start at given time, no errors.

Found another car heater:
[https://snillevilla.se/automations/11188/](url)

Worked!
