### ISSUE TITLE
86 compatible?

### ISSUE THREAD

**Issue by timcv** [Gnaget2/Car-Heater-Package#5]
Hi,

This package looks great!

Is it compatible with HA 86,4 lovelace?

//Tim

**Comment by Gnaget2** [comment]
yes and no, 

it is working in latest versions of hass but if you add it after the automatic mifration to LL you have to manuall add it to you LL gui.

`  - badges: []
    cards:
      - entities:
          - entity: input_number.heater_hour
          - entity: input_number.heater_minutes
          - entity: sensor.departuretime
          - entity: sensor.netatmo_ute_temperature
            name: Utomhustemperatur
          - entity: input_boolean.heaterstatus
          - entity: input_boolean.heaterweekday
          - entity: switch.motorvarmaren
        show_header_toggle: false
        title: Car
        type: entities`

that is my config (raw data) for the LL gui, you need to change the temp sensor to fit your config

**Comment by timcv** [comment]
Thank you!

I got warnings for platform: time.

I changed time to time_pattern one some of the automations.

//Tim

**Comment by Gnaget2** [comment]
i have nw updated repo to use time_pattern

**Comment by timcv** [comment]
Thanks for sharing your code!
